#!/bin/sh

## hyphop ##

#= build lakka for edge

FAIL(){
    echo "[e] $@">&2
    exit 1
}

REPO=Lakka-LibreELEC

cd ../

[ -d "$REPO" ] || {
    git clone https://github.com/hyphop/$REPO || FAIL git
    git checkout edge
}

#cd -

cd $REPO

# sudo apt-get install texinfo
# sudo apt-get install gcc-multilib

export PROJECT=Amlogic
export DEVICE=AMLG12
export ARCH=aarch64
export UBOOT_SYSTEM=
export KHADAS=1

make image || FAIL make lakka

