#!/bin/sh

## hyphop ##

#= build lakka for edge

FAIL(){
    echo "[e] $@">&2
    exit 1
}

REPO=Lakka-LibreELEC
BRANCH=origin/Lakka-v3.0
BRANCH=origin/edge-v3-new

export PROJECT=Rockchip
export DEVICE=RK3399
export ARCH=arm
export UBOOT_SYSTEM=khadas-edge
export BOARD=Edge

export NO_CORES="mesen picodrive"

echo "NO_CORES: $NO_CORES"

(
cd ../

[ -d "$REPO" ] || {
    git clone https://github.com/hyphop/$REPO || FAIL git
    git checkout $BRANCH
}

cd $REPO

# sudo apt-get install texinfo
P=picodrive
P=mrboom
P=mame2015
P=gpsp

#scripts/build $P || FAIL boom

make image || FAIL make lakka

) || exit 

#exit 0

(
[ "$CMP_ARGS" ] || \
    CMP_ARGS=-8
export CMP_ARGS=$CMP_ARGS
export SUF=pre.$ARCH.sd.emmc.img
export UBOOT_TYPE=mainline
cd scripts
./build_image
)
