#!/bin/sh

## hyphop ##

#= build lakka for edge

FAIL(){
    echo "[e] $@">&2
    exit 1
}

REPO=Lakka-LibreELEC
BRANCH=origin/Lakka-v3.0

(
cd ../

[ -d "$REPO" ] || {
    git clone https://github.com/hyphop/$REPO || FAIL git
    git checkout $BRANCH
}

cd $REPO

# sudo apt-get install texinfo

export PROJECT=Rockchip
export DEVICE=RK3399
export ARCH=arm
export UBOOT_SYSTEM=khadas-edge

make image || FAIL make lakka
)

#./scripts/build_image
