#!/bin/sh

## hyphop ##

#= build lakka for edge

FAIL(){
    echo "[e] $@">&2
    exit 1
}

REPO=Lakka-LibreELEC

cd ../

[ -d "$REPO" ] || {
    git clone https://github.com/hyphop/$REPO || FAIL git
    git checkout edge
}

#cd -

cd $REPO

# sudo apt-get install texinfo

export PROJECT=Amlogic
export DEVICE=AMLGX
export ARCH=arm
export UBOOT_SYSTEM=

# meson-gxm-khadas-vim2.dtb
# meson-gxl-s905x-khadas-vim.dtb

make image || FAIL make lakka

