#!/bin/sh

IN="$1"

[ "$IN" ] || exit

[ "$BOARD" ] || BOARD=Edge

case $IN in
    Edge*)
    BOARD=Edge
    ;;
    VIM3l*|VIM3L*)
    BOARD=VIM3L
    ;;
    VIM3*)
    BOARD=VIM3
    ;;
    VIM2*)
    BOARD=VIM2
    ;;
    *)
    BOARD=VIM1
    ;;
esac


echo "+ $IN"

    ./xze "$IN" -3 -f \
	-M \
	\##KRESCUE_META## \
	label=$LABEL \
	image="${IN%.*}" \
	builder=hyphop \
	date="$(TZ= date)" \
	match=BOARD=$BOARD \
	link=http://dl.khadas.com/ \
	duration=60 \
	desc="$LABEL game console for Khadas $BOARD board aarch64...." \
	\##KRESCUE-META## \
	\##KRESCUE##END
